language: node_js
node_js:
  - 8.10.0
# Travis-CI Caching
cache:
  directories:
  - node_modules

before_install:
  - cd RepairVue

# S: Build Lifecycle
install:
  - npm i npm@latest -g
  - npm install

before_script:


script:
  - npm run build

